# Source: free5gc/charts/nrf/charts/mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: default/mongodb
  name: mongodb
  namespace: free5gc-cp
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.7.0
    app.kubernetes.io/instance: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|mongodb'
secrets:
- name: mongodb
