# Source: free5gc/charts/nrf/charts/mongodb/templates/standalone/svc.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: default/mongodb
  name: mongodb
  namespace: free5gc-cp
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.7.0
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/component: mongodb
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|mongodb'
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
    nodePort: null
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: free5gc
    app.kubernetes.io/component: mongodb
